### ISSUE TITLE
ロシア語検索機能を追加する

### ISSUE THREAD

**Issue by naon708** [naon708/search_app_nuxt#52]
## 概要
- Pinapリリース当時は政治的観点からロシア語検索機能を制限した
- そろそろ良かろうということで機能を追加する

## TODO
- [x] BEの修正が必要か調査
- [x] 検索モーダルに「ロシア語で検索」ボタンを追加
- [x] BEとの疎通

## 本番動作確認
- [x] 演目一覧
    - [x] ロシア語カラムがある演目はボタンが表示され、ロシア語で検索されること
    - [x] ロシア語カラムが無い演目はボタンが表示されないこと
- [x] ダンサー一覧
    - [x] ロシア語カラムがある演目はボタンが表示され、ロシア語で検索されること
    - [x] ロシア語カラムが無い演目はボタンが表示されないこと
- [x] ステップ・ヴァリエーションは変更がないこと

## PR
https://github.com/naon708/search_app_nuxt/pull/55

**Comment by naon708** [comment]
本番動作確認DONE 🎉

**Comment by naon708** [comment]
TODO: アプリ内検索結果ページも改修が必要だったため対応する

**Comment by naon708** [comment]
## 残タスク

### ロシア語検索のnewアイコンを3ヶ月くらい経ったら消す(2023/4リリース)

- [ ] components/contents/cards/Dialog.vue
- [ ] pages/contents/programs.vue
- [ ] pages/contents/dancers.vue
