### ISSUE TITLE
画像ファイルをassets配下に移行する

### ISSUE THREAD

**Issue by naon708** [naon708/search_app_nuxt#57]
## 概要
- staticディレクトリに配置されている画像が表示されない事象が発生した
- assetsに配置したところ解決した
- assetsの方が推奨されているっぽいので移行したほうが良さそう
- ページで表示している画像を移行する(OGP専用画像は除く)

```html
<!-- 1. /assets/images/ に画像ファイルを配置 -->

<!-- 2. requireで囲ってbindさせる -->
<v-img :src="require('~/assets/images/hoge.JPEG')" alt="hoge">
```

## TODO
- [x] static/pinap_icon_v2.png
- [x] static/profile.JPG
- [x] static/swan.png

## 本番動作確認
- [x] ページアクセス時に画像が表示されていること
- [x] ブラウザをリロードした際に画像が表示されること

## 調査
- パスの指定には`@`より`~`が推奨されている
  - https://nuxtjs.org/ja/docs/directory-structure/assets#webpack
- `v-img`とパスの指定方法で相性があるらしい
- `img`と`v-img`の挙動の違いに注意
  - https://qiita.com/hiroyukiwk/items/a26e767d193ef8d9155b#vuetify%E3%81%AEv-img%E3%81%A7%E7%94%BB%E5%83%8F%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B
- **画像ファイルのパスが正しく解決されていなかった**
- **`assets`ディレクトリに画像ファイルを配置し、`require`を使って画像ファイルを読み込むことでビルド時にWebpackが画像ファイルの正しいパスを生成し、リロード時の問題が解決される**

**Comment by naon708** [comment]
## PR
https://github.com/naon708/search_app_nuxt/pull/58
